FROM confluentinc/cp-kafka-connect-base:7.2.14

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-mqtt:latest